force-app/main/default/objects/Account/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>This field defines how much points a user have</description>
    <label>Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Attendees__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Product2/fields/Points_Needed__c.field-meta.xml
<CustomField>
    <fullName>Points_Needed__c</fullName>
    <description>This field defines how much points a user need to redeem the swag</description>
    <label>Points Needed</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Static_Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Static_Resource_Name__c</fullName>
    <label>Static Resource Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Redeem_Product__c/Redeem_Product__c.object-meta.xml
<CustomObject>
    <label>Redeem Product</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Redeem Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Redeem Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Redeem_Product__c/fields/Event_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Event_Attendee__c</fullName>
    <label>Event Attendee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Redeem_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Redeem Products</relationshipLabel>
    <relationshipName>Redeem_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GetSwagsHandler.cls
public with sharing class GetSwagsHandler {

    public class SwagsException extends Exception {}

    public class UserDetails {
        @AuraEnabled
        public String name {get;set;}
        @AuraEnabled
        public Integer userCurrentPoints {get;set;}
        @AuraEnabled
        public List<SwagWrapper> swagsList {get;set;}

        public UserDetails(String name, Integer userCurrentPoints, List<SwagWrapper> swagsList) {
            this.name = name;
            this.userCurrentPoints = userCurrentPoints;
            this.swagsList = swagsList;
        }
    }

    public class SwagWrapper {
        @AuraEnabled
        public String name {get;set;}
        @AuraEnabled
        public Integer userCurrentPoints {get;set;}
        @AuraEnabled
        public Boolean quantityNotAvailable {get;set;}
        @AuraEnabled
        public String imageUrl {get;set;}
        @AuraEnabled
        public Integer pointsNeeded {get;set;}
        @AuraEnabled
        public Boolean showClaimSwagBtn {get;set;}
        @AuraEnabled
        public Boolean isClaimed {get;set;}

        public SwagWrapper(String name, Integer userCurrentPoints, Boolean quantityNotAvailable, String imageUrl, Integer pointsNeeded, Boolean showClaimSwagBtn, Boolean isClaimed) {
            this.name = name;
            this.userCurrentPoints = userCurrentPoints;
            this.quantityNotAvailable = quantityNotAvailable;
            this.imageUrl = imageUrl;
            this.pointsNeeded = pointsNeeded;
            this.showClaimSwagBtn = showClaimSwagBtn;
            this.isClaimed = isClaimed;
        }
    }

    // This function will return data in UserDetails wrapper
    @AuraEnabled
    public static UserDetails getSwags(String accountId) {
        try {
            // First get the account details using account id
            Event_Attendees__c account = [SELECT Name, Points__c FROM Event_Attendees__c WHERE Id = :accountId LIMIT 1];
            // Now convert the points coming in Decimal format to Integer
            Integer points = Integer.valueOf(account.Points__c);

            // Create a list of SwagWrapper to return in the response
            List<SwagWrapper> swagsList = new List<SwagWrapper>();

            // Now get all the products from the org
            List<Product2> productList = [SELECT Id, Name, Quantity_Available__c, Static_Resource_Name__c, Points_Needed__c FROM Product2];

            // Now get all the redeemed products which user have already claimed
            List<Redeem_Product__c> redeemProductList = [SELECT Product__c FROM Redeem_Product__c WHERE Event_Attendee__c = :accountId];
            // Create a map of product id to claimed status map
            // This map will identifies whether a product is claimed or not
            Map<Id, Boolean> redeemProductMap = new Map<Id, Boolean>();
            for (Redeem_Product__c redeemProduct : redeemProductList) {
                redeemProductMap.put(redeemProduct.Product__c, true);
            }

            // Get the org domain url, this will help us to construct image of the product from static resource
            String orgUrl = URL.getOrgDomainUrl().toExternalForm();

            // Now iterate through the products list and one-by-one add them to the swagsList
            for (Product2 product : productList) {
                swagsList.add(new SwagWrapper(
                    product.Name,
                    points,
                    Integer.valueOf(product.Quantity_Available__c) <= 0,
                    orgUrl + '/resource/' + EncodingUtil.urlEncode(product.Static_Resource_Name__c, 'UTF-8'),
                    Integer.valueOf(product.Points_Needed__c),
                    !(points >= Integer.valueOf(product.Points_Needed__c) && Integer.valueOf(product.Quantity_Available__c) > 0),
                    redeemProductMap.containsKey(product.Id)
                ));
            }

            // Simply return UserDetails at the end
            return new UserDetails(account.Name, Integer.valueOf(account.Points__c), swagsList);
        } catch (Exception e) {
            throw new SwagsException(e.getMessage());
        }
    }

}